version: '3'
services:
  web:
    image: ${REPO_SERVER}/scnr/web:latest
    expose:
      - 80
    env_file:
      - environment.${ENVIRONMENT_FILE}.env
      - ports.env
      - services.${SERVICES_FILE}.env
    environment:
      - JWT_PUB_KEY=$JWT_PUB_KEY
      - VIRTUAL_HOST=$VIRTUAL_HOST_ALL
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/
    logging:
      options:
        max-size: "10m"
