name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_SERVER: ${{secrets.DOCKER_SERVER}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_SERVER
    
    - name: Build the Docker image
      run: docker build src/SCNRWeb --file src/SCNRWeb/Dockerfile --tag scnr/web:$(date +%s)

    - name: Push image
      run: docker push scnr/web
      
